CREATE TABLE modifier (
    id BIGSERIAL PRIMARY KEY,
    description VARCHAR(180) NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
