// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bomitems.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBomItem = `-- name: CreateBomItem :one
INSERT INTO bom_items (
    id,
    bom_id,
    component_id,
    quantity,
    uom,
    scrap_percent,
    operation_id,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
RETURNING id, bom_id, component_id, quantity, uom, scrap_percent, operation_id, created_at
`

type CreateBomItemParams struct {
	ID           int64
	BomID        int64
	ComponentID  int64
	Quantity     string
	Uom          sql.NullString
	ScrapPercent string
	OperationID  int64
}

func (q *Queries) CreateBomItem(ctx context.Context, arg CreateBomItemParams) (BomItem, error) {
	row := q.db.QueryRowContext(ctx, createBomItem,
		arg.ID,
		arg.BomID,
		arg.ComponentID,
		arg.Quantity,
		arg.Uom,
		arg.ScrapPercent,
		arg.OperationID,
	)
	var i BomItem
	err := row.Scan(
		&i.ID,
		&i.BomID,
		&i.ComponentID,
		&i.Quantity,
		&i.Uom,
		&i.ScrapPercent,
		&i.OperationID,
		&i.CreatedAt,
	)
	return i, err
}
