// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generate_mask.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertProductMask = `-- name: InsertProductMask :one
INSERT INTO product_masks (
    product_code, 
    mask, 
    mask_hash, 
    created_by, 
    created_at
    )
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, product_code, mask, mask_hash, created_by, created_at
`

type InsertProductMaskParams struct {
	ProductCode string
	Mask        string
	MaskHash    string
	CreatedBy   uuid.UUID
}

func (q *Queries) InsertProductMask(ctx context.Context, arg InsertProductMaskParams) (ProductMask, error) {
	row := q.db.QueryRowContext(ctx, insertProductMask,
		arg.ProductCode,
		arg.Mask,
		arg.MaskHash,
		arg.CreatedBy,
	)
	var i ProductMask
	err := row.Scan(
		&i.ID,
		&i.ProductCode,
		&i.Mask,
		&i.MaskHash,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertProductMaskAnswer = `-- name: InsertProductMaskAnswer :exec
INSERT INTO product_mask_answers (mask_id, question_id, option_id, position)
VALUES ($1, $2, $3, $4)
`

type InsertProductMaskAnswerParams struct {
	MaskID     int64
	QuestionID int64
	OptionID   int64
	Position   int
}

func (q *Queries) InsertProductMaskAnswer(ctx context.Context, arg InsertProductMaskAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertProductMaskAnswer,
		arg.MaskID,
		arg.QuestionID,
		arg.OptionID,
		arg.Position,
	)
	return err
}
