// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    id,
    warehouse_id,
    code,
    name,
    description,
    type,
    status,
    health,
    created_by,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    NOW()
)
RETURNING id, warehouse_id, code, name, description, type, status, health, created_by, created_at
`

type CreateItemParams struct {
	ID          int64
	WarehouseID int32
	Code        string
	Name        string
	Description string
	Type        string
	Status      string
	Health      string
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.WarehouseID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Health,
		arg.CreatedBy,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Health,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
