// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_questions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const associateQuestionItem = `-- name: AssociateQuestionItem :exec
INSERT INTO item_questions (
    item_code,
    question_id,
    position,
    created_at
) VALUES ($1, $2, $3, $4)
`

type AssociateQuestionItemParams struct {
	ItemCode   int64
	QuestionID int64
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) AssociateQuestionItem(ctx context.Context, arg AssociateQuestionItemParams) error {
	_, err := q.db.Exec(ctx, associateQuestionItem,
		arg.ItemCode,
		arg.QuestionID,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const existsByItemAndPosition = `-- name: ExistsByItemAndPosition :one
SELECT EXISTS (
    SELECT 1
    FROM item_questions
    WHERE item_code = $1
      AND position = $2
)
`

type ExistsByItemAndPositionParams struct {
	ItemCode int64
	Position int32
}

func (q *Queries) ExistsByItemAndPosition(ctx context.Context, arg ExistsByItemAndPositionParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByItemAndPosition, arg.ItemCode, arg.Position)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByItemAndQuestion = `-- name: ExistsByItemAndQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM item_questions
    WHERE item_code = $1
      AND question_id = $2
)
`

type ExistsByItemAndQuestionParams struct {
	ItemCode   int64
	QuestionID int64
}

func (q *Queries) ExistsByItemAndQuestion(ctx context.Context, arg ExistsByItemAndQuestionParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByItemAndQuestion, arg.ItemCode, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getQuestionsByItemCode = `-- name: GetQuestionsByItemCode :many
SELECT iq.item_code, iq.question_id, iq.position, iq.created_at, q.name AS question_name
FROM item_questions iq
JOIN questions q ON q.id = iq.question_id
JOIN items i ON i.id = iq.item_code
WHERE i.code = $1
ORDER BY iq.position
`

type GetQuestionsByItemCodeRow struct {
	ItemCode     int64
	QuestionID   int64
	Position     int32
	CreatedAt    pgtype.Timestamptz
	QuestionName string
}

func (q *Queries) GetQuestionsByItemCode(ctx context.Context, code int64) ([]GetQuestionsByItemCodeRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsByItemCode, code)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsByItemCodeRow
	for rows.Next() {
		var i GetQuestionsByItemCodeRow
		if err := rows.Scan(
			&i.ItemCode,
			&i.QuestionID,
			&i.Position,
			&i.CreatedAt,
			&i.QuestionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllItemQuestions = `-- name: ListAllItemQuestions :many
SELECT iq.item_code, iq.question_id, iq.position, iq.created_at,
       i.code AS item_business_code, q.name AS question_name
FROM item_questions iq
JOIN questions q ON q.id = iq.question_id
JOIN items i ON i.id = iq.item_code
ORDER BY i.code, iq.position
`

type ListAllItemQuestionsRow struct {
	ItemCode         int64
	QuestionID       int64
	Position         int32
	CreatedAt        pgtype.Timestamptz
	ItemBusinessCode int64
	QuestionName     string
}

func (q *Queries) ListAllItemQuestions(ctx context.Context) ([]ListAllItemQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listAllItemQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllItemQuestionsRow
	for rows.Next() {
		var i ListAllItemQuestionsRow
		if err := rows.Scan(
			&i.ItemCode,
			&i.QuestionID,
			&i.Position,
			&i.CreatedAt,
			&i.ItemBusinessCode,
			&i.QuestionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
