package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// ─── structs ──────────────────────────────────────────────────────────────────
// NOTE: MaintenanceFrequencyEnum and MaintenanceOrderStatusEnum are generated by
// sqlc in models.go. Do NOT redeclare them here.

type DBMaintenancePlan struct {
	ID              int64
	Code            int64
	MachineID       int64
	WorkCenterID    pgtype.Int8
	Description     string
	Frequency       MaintenanceFrequencyEnum
	FrequencyDays   int32
	EstimatedHours  float64
	LastExecutedAt  pgtype.Timestamptz
	NextScheduledAt pgtype.Timestamptz
	IsActive        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

type DBMaintenanceOrder struct {
	ID             int64
	PlanID         int64
	MachineID      pgtype.Int8
	WorkCenterID   pgtype.Int8
	ScheduledDate  pgtype.Date
	EstimatedHours float64
	ActualHours    pgtype.Float8
	Status         MaintenanceOrderStatusEnum
	StartedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	Notes          pgtype.Text
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// ─── maintenance_plans ────────────────────────────────────────────────────────

const createMaintenancePlan = `
INSERT INTO maintenance_plans
(machine_id, work_center_id, description, frequency, frequency_days, estimated_hours, next_scheduled_at, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, code, machine_id, work_center_id, description, frequency, frequency_days, estimated_hours,
          last_executed_at, next_scheduled_at, is_active, created_at, updated_at, created_by`

type CreateMaintenancePlanParams struct {
	MachineID       int64
	WorkCenterID    pgtype.Int8
	Description     string
	Frequency       MaintenanceFrequencyEnum
	FrequencyDays   int32
	EstimatedHours  float64
	NextScheduledAt pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreateMaintenancePlan(ctx context.Context, arg CreateMaintenancePlanParams) (DBMaintenancePlan, error) {
	row := q.db.QueryRow(ctx, createMaintenancePlan,
		arg.MachineID, arg.WorkCenterID, arg.Description, arg.Frequency,
		arg.FrequencyDays, arg.EstimatedHours, arg.NextScheduledAt, arg.CreatedBy,
	)
	return scanMaintenancePlan(row)
}

const updateMaintenancePlan = `
UPDATE maintenance_plans SET
    description     = $2,
    frequency       = $3,
    frequency_days  = $4,
    estimated_hours = $5,
    next_scheduled_at = $6,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, code, machine_id, work_center_id, description, frequency, frequency_days, estimated_hours,
          last_executed_at, next_scheduled_at, is_active, created_at, updated_at, created_by`

type UpdateMaintenancePlanParams struct {
	ID              int64
	Description     string
	Frequency       MaintenanceFrequencyEnum
	FrequencyDays   int32
	EstimatedHours  float64
	NextScheduledAt pgtype.Timestamptz
}

func (q *Queries) UpdateMaintenancePlan(ctx context.Context, arg UpdateMaintenancePlanParams) (DBMaintenancePlan, error) {
	row := q.db.QueryRow(ctx, updateMaintenancePlan,
		arg.ID, arg.Description, arg.Frequency, arg.FrequencyDays, arg.EstimatedHours, arg.NextScheduledAt,
	)
	return scanMaintenancePlan(row)
}

const getMaintenancePlanByID = `
SELECT id, code, machine_id, work_center_id, description, frequency, frequency_days, estimated_hours,
       last_executed_at, next_scheduled_at, is_active, created_at, updated_at, created_by
FROM maintenance_plans WHERE id = $1`

func (q *Queries) GetMaintenancePlanByID(ctx context.Context, id int64) (DBMaintenancePlan, error) {
	row := q.db.QueryRow(ctx, getMaintenancePlanByID, id)
	return scanMaintenancePlan(row)
}

const listMaintenancePlans = `
SELECT id, code, machine_id, work_center_id, description, frequency, frequency_days, estimated_hours,
       last_executed_at, next_scheduled_at, is_active, created_at, updated_at, created_by
FROM maintenance_plans
WHERE ($1::boolean IS NULL OR is_active = $1)
ORDER BY machine_id, next_scheduled_at`

func (q *Queries) ListMaintenancePlans(ctx context.Context, onlyActive *bool) ([]DBMaintenancePlan, error) {
	rows, err := q.db.Query(ctx, listMaintenancePlans, onlyActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanMaintenancePlans(rows)
}

const listMaintenancePlansByMachine = `
SELECT id, code, machine_id, work_center_id, description, frequency, frequency_days, estimated_hours,
       last_executed_at, next_scheduled_at, is_active, created_at, updated_at, created_by
FROM maintenance_plans WHERE machine_id = $1 AND is_active = TRUE
ORDER BY next_scheduled_at`

func (q *Queries) ListMaintenancePlansByMachine(ctx context.Context, machineID int64) ([]DBMaintenancePlan, error) {
	rows, err := q.db.Query(ctx, listMaintenancePlansByMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanMaintenancePlans(rows)
}

const deactivateMaintenancePlan = `UPDATE maintenance_plans SET is_active=FALSE, updated_at=NOW() WHERE id=$1`

func (q *Queries) DeactivateMaintenancePlan(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateMaintenancePlan, id)
	return err
}

// ─── maintenance_orders ───────────────────────────────────────────────────────

const createMaintenanceOrder = `
INSERT INTO maintenance_orders (plan_id, machine_id, work_center_id, scheduled_date, estimated_hours)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, plan_id, machine_id, work_center_id, scheduled_date, estimated_hours, actual_hours,
          status, started_at, completed_at, notes, is_active, created_at, updated_at`

type CreateMaintenanceOrderParams struct {
	PlanID         int64
	MachineID      pgtype.Int8
	WorkCenterID   pgtype.Int8
	ScheduledDate  pgtype.Date
	EstimatedHours float64
}

func (q *Queries) CreateMaintenanceOrder(ctx context.Context, arg CreateMaintenanceOrderParams) (DBMaintenanceOrder, error) {
	row := q.db.QueryRow(ctx, createMaintenanceOrder,
		arg.PlanID, arg.MachineID, arg.WorkCenterID, arg.ScheduledDate, arg.EstimatedHours,
	)
	return scanMaintenanceOrder(row)
}

const updateMaintenanceOrder = `
UPDATE maintenance_orders SET
    status       = $2,
    actual_hours = $3,
    started_at   = $4,
    completed_at = $5,
    notes        = $6,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, plan_id, machine_id, work_center_id, scheduled_date, estimated_hours, actual_hours,
          status, started_at, completed_at, notes, is_active, created_at, updated_at`

type UpdateMaintenanceOrderParams struct {
	ID          int64
	Status      MaintenanceOrderStatusEnum
	ActualHours pgtype.Float8
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	Notes       pgtype.Text
}

func (q *Queries) UpdateMaintenanceOrder(ctx context.Context, arg UpdateMaintenanceOrderParams) (DBMaintenanceOrder, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceOrder,
		arg.ID, arg.Status, arg.ActualHours, arg.StartedAt, arg.CompletedAt, arg.Notes,
	)
	return scanMaintenanceOrder(row)
}

const getMaintenanceOrderByID = `
SELECT id, plan_id, machine_id, work_center_id, scheduled_date, estimated_hours, actual_hours,
       status, started_at, completed_at, notes, is_active, created_at, updated_at
FROM maintenance_orders WHERE id = $1`

func (q *Queries) GetMaintenanceOrderByID(ctx context.Context, id int64) (DBMaintenanceOrder, error) {
	row := q.db.QueryRow(ctx, getMaintenanceOrderByID, id)
	return scanMaintenanceOrder(row)
}

const listMaintenanceOrdersByPlan = `
SELECT id, plan_id, machine_id, work_center_id, scheduled_date, estimated_hours, actual_hours,
       status, started_at, completed_at, notes, is_active, created_at, updated_at
FROM maintenance_orders WHERE plan_id = $1 AND is_active = TRUE
ORDER BY scheduled_date`

func (q *Queries) ListMaintenanceOrdersByPlan(ctx context.Context, planID int64) ([]DBMaintenanceOrder, error) {
	rows, err := q.db.Query(ctx, listMaintenanceOrdersByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanMaintenanceOrders(rows)
}

const listMaintenanceOrdersByWorkCenter = `
SELECT id, plan_id, machine_id, work_center_id, scheduled_date, estimated_hours, actual_hours,
       status, started_at, completed_at, notes, is_active, created_at, updated_at
FROM maintenance_orders
WHERE work_center_id = $1 AND scheduled_date BETWEEN $2 AND $3 AND is_active = TRUE
ORDER BY scheduled_date`

func (q *Queries) ListMaintenanceOrdersByWorkCenter(ctx context.Context, workCenterID int64, from, to pgtype.Date) ([]DBMaintenanceOrder, error) {
	rows, err := q.db.Query(ctx, listMaintenanceOrdersByWorkCenter, workCenterID, from, to)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanMaintenanceOrders(rows)
}

const existsOrderForPlanAndDate = `
SELECT EXISTS(
    SELECT 1 FROM maintenance_orders
    WHERE plan_id = $1
      AND scheduled_date = $2::date
      AND status <> 'CANCELLED'
      AND is_active = TRUE
)`

func (q *Queries) ExistsOrderForPlanAndDate(ctx context.Context, planID int64, date time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, existsOrderForPlanAndDate, planID, date.Format("2006-01-02"))
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

// GetBlockedHoursOnDate returns sum of estimated_hours for planned/in-progress
// maintenance orders for a work center on a specific date — used by CRP.
const getBlockedHoursOnDate = `
SELECT COALESCE(SUM(estimated_hours), 0)
FROM maintenance_orders
WHERE work_center_id = $1
  AND scheduled_date = $2::date
  AND status IN ('PLANNED', 'IN_PROGRESS')
  AND is_active = TRUE`

func (q *Queries) GetBlockedHoursOnDate(ctx context.Context, workCenterID int64, date time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, getBlockedHoursOnDate, workCenterID, date.Format("2006-01-02"))
	var hours float64
	err := row.Scan(&hours)
	return hours, err
}

// ─── scanners ─────────────────────────────────────────────────────────────────

type scannerRow interface{ Scan(...any) error }

func scanMaintenancePlan(row scannerRow) (DBMaintenancePlan, error) {
	var i DBMaintenancePlan
	err := row.Scan(
		&i.ID, &i.Code, &i.MachineID, &i.WorkCenterID, &i.Description,
		&i.Frequency, &i.FrequencyDays, &i.EstimatedHours,
		&i.LastExecutedAt, &i.NextScheduledAt, &i.IsActive,
		&i.CreatedAt, &i.UpdatedAt, &i.CreatedBy,
	)
	return i, err
}

func scanMaintenancePlans(rows interface {
	Next() bool
	Scan(...any) error
	Err() error
}) ([]DBMaintenancePlan, error) {
	var items []DBMaintenancePlan
	for rows.Next() {
		p, err := scanMaintenancePlan(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

func scanMaintenanceOrder(row scannerRow) (DBMaintenanceOrder, error) {
	var i DBMaintenanceOrder
	err := row.Scan(
		&i.ID, &i.PlanID, &i.MachineID, &i.WorkCenterID, &i.ScheduledDate,
		&i.EstimatedHours, &i.ActualHours, &i.Status,
		&i.StartedAt, &i.CompletedAt, &i.Notes,
		&i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

func scanMaintenanceOrders(rows interface {
	Next() bool
	Scan(...any) error
	Err() error
}) ([]DBMaintenanceOrder, error) {
	var items []DBMaintenanceOrder
	for rows.Next() {
		o, err := scanMaintenanceOrder(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, o)
	}
	return items, rows.Err()
}
