// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bom struct {
	ID        int64
	ProductID int64
	BomType   string
	Version   int32
	Status    string
	ValidFrom sql.NullTime
	CreatedAt time.Time
	Mask      int64
}

type BomItem struct {
	ID            int64
	BomID         int64
	ComponentID   int64
	Quantity      string
	Uom           sql.NullString
	ScrapPercent  string
	OperationID   int64
	CreatedAt     time.Time
	MaskComponent int64
}

type ComplementA struct {
	ID    int64
	Value string
}

type ComplementB struct {
	ID    int64
	Value string
}

type Component struct {
	ID        int64
	Code      string
	Warehouse sql.NullInt64
	GroupCode string
	Name      string
	Type      interface{}
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type ComponentMask struct {
	ID          int64
	ComponentID int64
	Mask        string
	MaskHash    string
	BusinessID  string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type MaskComposition struct {
	ParentMaskID int64
	ChildMaskID  int64
	Quantity     string
}

type MaterialConsumption struct {
	ComponentMaskID int64
	MaterialID      int64
	Quantity        string
	Unit            string
}

type MrpParameter struct {
	ProductID    int64
	PlanningType string
	LeadTimeDays int32
	SafetyStock  string
}

type Operation struct {
	ID   int64
	Code string
	Name string
}

type Product struct {
	ID        int64
	Code      string
	GroupCode sql.NullString
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type ProductMask struct {
	ID          int64
	ProductCode string
	Mask        string
	MaskHash    string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type ProductMaskAnswer struct {
	ID         int64
	QuestionID int64
	OptionID   int64
	Position   int32
	MaskID     int64
}

type ProductQuestion struct {
	ProductID  int64
	QuestionID int64
	Position   int32
	CreatedAt  time.Time
}

type ProductQuestionAnswer struct {
	ID         int64
	ProductID  int64
	QuestionID int64
	Answer     string
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}

type ProductionOrder struct {
	ID                 int64
	ProductID          int64
	BomID              int64
	Quantity           string
	Status             string
	CurrentOperationID sql.NullInt64
	CreatedAt          time.Time
}

type Question struct {
	ID            int64
	Name          string
	Createdby     uuid.UUID
	ComplementAID int64
	ComplementBID int64
	CreatedAt     time.Time
}

type QuestionOption struct {
	ID         int64
	QuestionID int64
	Value      string
	CreatedAt  time.Time
	CreatedBy  uuid.UUID
}

type Stock struct {
	ProductID int64
	Quantity  string
}

type StockMovement struct {
	ID            int64
	ProductID     int64
	MovementType  string
	Quantity      string
	ReferenceType sql.NullString
	ReferenceID   sql.NullInt64
	CreatedAt     time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
