// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Component struct {
	ID        int64
	Code      string
	Name      string
	Type      interface{}
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type ComponentMask struct {
	ID          int64
	ComponentID int64
	Mask        string
	MaskHash    string
	BusinessID  string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type MaskComposition struct {
	ParentMaskID int64
	ChildMaskID  int64
	Quantity     string
}

type MaterialConsumption struct {
	ComponentMaskID int64
	MaterialID      int64
	Quantity        string
	Unit            string
}

type Product struct {
	ID        int64
	Code      string
	GroupCode sql.NullString
	Name      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProductMask struct {
	ID          int64
	ProductID   int64
	ProductCode string
	Mask        string
	MaskHash    string
	BusinessID  string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type ProductQuestion struct {
	ProductID  int64
	QuestionID int64
	Position   int32
	CreatedAt  time.Time
}

type ProductQuestionAnswer struct {
	ID         int64
	ProductID  int64
	QuestionID int64
	Answer     string
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}

type Question struct {
	ID        int64
	Name      string
	Createdby uuid.UUID
	CreatedAt time.Time
}

type QuestionOption struct {
	ID         int64
	QuestionID int64
	Value      string
	CreatedAt  time.Time
	Createdby  uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
