// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_questions.sql

package sqlc

import (
	"context"
	"time"
)

const associateQuestionProduct = `-- name: AssociateQuestionProduct :exec
INSERT INTO product_questions (
    product_id,
    question_id,
    position,
    created_at
) VALUES ($1, $2, $3, $4)
`

type AssociateQuestionProductParams struct {
	ProductID  int64
	QuestionID int64
	Position   int32
	CreatedAt  time.Time
}

func (q *Queries) AssociateQuestionProduct(ctx context.Context, arg AssociateQuestionProductParams) error {
	_, err := q.db.ExecContext(ctx, associateQuestionProduct,
		arg.ProductID,
		arg.QuestionID,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const existsByProductAndPosition = `-- name: ExistsByProductAndPosition :one
SELECT EXISTS (
    SELECT 1
    FROM product_questions
    WHERE product_id = $1
      AND position = $2
)
`

type ExistsByProductAndPositionParams struct {
	ProductID int64
	Position  int32
}

func (q *Queries) ExistsByProductAndPosition(ctx context.Context, arg ExistsByProductAndPositionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByProductAndPosition, arg.ProductID, arg.Position)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByProductAndQuestion = `-- name: ExistsByProductAndQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM product_questions
    WHERE product_id = $1
      AND question_id = $2
)
`

type ExistsByProductAndQuestionParams struct {
	ProductID  int64
	QuestionID int64
}

func (q *Queries) ExistsByProductAndQuestion(ctx context.Context, arg ExistsByProductAndQuestionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByProductAndQuestion, arg.ProductID, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
