// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_mask.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProductMask = `-- name: CreateProductMask :one
INSERT INTO product_masks (
    id,
    product_id,
    mask,
    mask_hash,
    business_id,
    created_by,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW()
)
RETURNING id, product_id, product_code, mask, mask_hash, business_id, created_by, created_at
`

type CreateProductMaskParams struct {
	ID         int64
	ProductID  int64
	Mask       string
	MaskHash   string
	BusinessID string
	CreatedBy  uuid.UUID
}

func (q *Queries) CreateProductMask(ctx context.Context, arg CreateProductMaskParams) (ProductMask, error) {
	row := q.db.QueryRowContext(ctx, createProductMask,
		arg.ID,
		arg.ProductID,
		arg.Mask,
		arg.MaskHash,
		arg.BusinessID,
		arg.CreatedBy,
	)
	var i ProductMask
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductCode,
		&i.Mask,
		&i.MaskHash,
		&i.BusinessID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductMask = `-- name: DeleteProductMask :exec
DELETE FROM product_masks
WHERE id = $1
`

func (q *Queries) DeleteProductMask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductMask, id)
	return err
}
