// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_questions.sql

package sqlc

import (
	"context"
	"time"
)

const createProductQuestion = `-- name: CreateProductQuestion :exec
INSERT INTO product_questions (
    product_id,
    question_id,
    position,
    created_at
) VALUES ($1, $2, $3, $4)
`

type CreateProductQuestionParams struct {
	ProductID  int64
	QuestionID int64
	Position   int32
	CreatedAt  time.Time
}

func (q *Queries) CreateProductQuestion(ctx context.Context, arg CreateProductQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createProductQuestion,
		arg.ProductID,
		arg.QuestionID,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const existsProductQuestionByProductAndPosition = `-- name: ExistsProductQuestionByProductAndPosition :one
SELECT EXISTS (
    SELECT 1
    FROM product_questions
    WHERE product_id = $1
      AND position = $2
)
`

type ExistsProductQuestionByProductAndPositionParams struct {
	ProductID int64
	Position  int32
}

func (q *Queries) ExistsProductQuestionByProductAndPosition(ctx context.Context, arg ExistsProductQuestionByProductAndPositionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsProductQuestionByProductAndPosition, arg.ProductID, arg.Position)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsProductQuestionByProductAndQuestion = `-- name: ExistsProductQuestionByProductAndQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM product_questions
    WHERE product_id = $1
      AND question_id = $2
)
`

type ExistsProductQuestionByProductAndQuestionParams struct {
	ProductID  int64
	QuestionID int64
}

func (q *Queries) ExistsProductQuestionByProductAndQuestion(ctx context.Context, arg ExistsProductQuestionByProductAndQuestionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsProductQuestionByProductAndQuestion, arg.ProductID, arg.QuestionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
