// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    name,
    createdby
) VALUES (
    $1,
    $2
) RETURNING id, name, createdby, complement_a_id, complement_b_id, created_at
`

type CreateQuestionParams struct {
	Name      string
	Createdby uuid.UUID
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.Name, arg.Createdby)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.ComplementAID,
		&i.ComplementBID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const existsQuestionByName = `-- name: ExistsQuestionByName :one
SELECT id, name, createdby, complement_a_id, complement_b_id, created_at
FROM questions
WHERE name = $1
`

func (q *Queries) ExistsQuestionByName(ctx context.Context, name string) (Question, error) {
	row := q.db.QueryRowContext(ctx, existsQuestionByName, name)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.ComplementAID,
		&i.ComplementBID,
		&i.CreatedAt,
	)
	return i, err
}

const findQuestionByName = `-- name: FindQuestionByName :one
SELECT id, name, createdby, complement_a_id, complement_b_id, created_at
FROM questions
WHERE name = $1
`

func (q *Queries) FindQuestionByName(ctx context.Context, name string) (Question, error) {
	row := q.db.QueryRowContext(ctx, findQuestionByName, name)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.ComplementAID,
		&i.ComplementBID,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, name, createdby, complement_a_id, complement_b_id, created_at
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.ComplementAID,
		&i.ComplementBID,
		&i.CreatedAt,
	)
	return i, err
}
