// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    name,
    createdby
) VALUES (
    $1,
    $2
) RETURNING id, name, createdby, created_at
`

type CreateQuestionParams struct {
	Name      string
	Createdby uuid.UUID
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.Name, arg.Createdby)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.CreatedAt,
	)
	return i, err
}
