// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions_options.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createQuestionOption = `-- name: CreateQuestionOption :one
INSERT INTO question_options (
    question_id,
    createdby,
    value
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, question_id, value, created_at, createdby
`

type CreateQuestionOptionParams struct {
	QuestionID int64
	Createdby  uuid.UUID
	Value      string
}

func (q *Queries) CreateQuestionOption(ctx context.Context, arg CreateQuestionOptionParams) (QuestionOption, error) {
	row := q.db.QueryRowContext(ctx, createQuestionOption, arg.QuestionID, arg.Createdby, arg.Value)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
		&i.Createdby,
	)
	return i, err
}

const deleteQuestionOption = `-- name: DeleteQuestionOption :exec
DELETE FROM question_options
WHERE id = $1
`

func (q *Queries) DeleteQuestionOption(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionOption, id)
	return err
}

const getQuestionOptionByID = `-- name: GetQuestionOptionByID :one
SELECT id, question_id, value, created_at, createdby
FROM question_options
WHERE id = $1
`

func (q *Queries) GetQuestionOptionByID(ctx context.Context, id int64) (QuestionOption, error) {
	row := q.db.QueryRowContext(ctx, getQuestionOptionByID, id)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Value,
		&i.CreatedAt,
		&i.Createdby,
	)
	return i, err
}
