// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: structure.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStructureComponent = `-- name: CreateStructureComponent :one
INSERT INTO item_structures (
    parent_item_id,
    parent_code,
    child_item_id,
    child_code,
    parent_mask,
    quantity,
    unit_of_measurement,
    loss_percentage,
    position,
    notes,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
`

type CreateStructureComponentParams struct {
	ParentItemID      int64
	ParentCode        string
	ChildItemID       int64
	ChildCode         string
	ParentMask        sql.NullString
	Quantity          float64
	UnitOfMeasurement string
	LossPercentage    float64
	Position          int32
	Notes             sql.NullString
	CreatedBy         uuid.UUID
}

func (q *Queries) CreateStructureComponent(ctx context.Context, arg CreateStructureComponentParams) (ItemStructure, error) {
	row := q.db.QueryRowContext(ctx, createStructureComponent,
		arg.ParentItemID,
		arg.ParentCode,
		arg.ChildItemID,
		arg.ChildCode,
		arg.ParentMask,
		arg.Quantity,
		arg.UnitOfMeasurement,
		arg.LossPercentage,
		arg.Position,
		arg.Notes,
		arg.CreatedBy,
	)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentItemID,
		&i.ChildItemID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Position,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
	)
	return i, err
}

const deactivateStructureComponent = `-- name: DeactivateStructureComponent :exec
UPDATE item_structures
SET
    is_active  = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStructureComponent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deactivateStructureComponent, id)
	return err
}

const getAllDirectChildren = `-- name: GetAllDirectChildren :many
SELECT id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
FROM item_structures
WHERE parent_item_id = $1
  AND is_active = TRUE
ORDER BY position, id
`

// Retorna TODOS os filhos ativos de um pai (genéricos + mascarados). (999)
func (q *Queries) GetAllDirectChildren(ctx context.Context, parentItemID int64) ([]ItemStructure, error) {
	rows, err := q.db.QueryContext(ctx, getAllDirectChildren, parentItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemStructure
	for rows.Next() {
		var i ItemStructure
		if err := rows.Scan(
			&i.ID,
			&i.ParentItemID,
			&i.ChildItemID,
			&i.ParentMask,
			&i.Quantity,
			&i.UnitOfMeasurement,
			&i.LossPercentage,
			&i.Position,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentCode,
			&i.ChildCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectChildrenForMask = `-- name: GetDirectChildrenForMask :many
SELECT id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
FROM item_structures
WHERE parent_item_id = $1
  AND is_active = TRUE
  AND (parent_mask = $2 OR parent_mask IS NULL)
ORDER BY
    -- Específicos primeiro, para facilitar a deduplicação na app layer
    CASE WHEN parent_mask IS NOT NULL THEN 0 ELSE 1 END,
    position,
    id
`

type GetDirectChildrenForMaskParams struct {
	ParentItemID int64
	ParentMask   sql.NullString
}

// Retorna filhos ativos de um pai para uma máscara específica E genéricos.
// A lógica de prioridade (específico > genérico) é aplicada na camada de aplicação.
func (q *Queries) GetDirectChildrenForMask(ctx context.Context, arg GetDirectChildrenForMaskParams) ([]ItemStructure, error) {
	rows, err := q.db.QueryContext(ctx, getDirectChildrenForMask, arg.ParentItemID, arg.ParentMask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemStructure
	for rows.Next() {
		var i ItemStructure
		if err := rows.Scan(
			&i.ID,
			&i.ParentItemID,
			&i.ChildItemID,
			&i.ParentMask,
			&i.Quantity,
			&i.UnitOfMeasurement,
			&i.LossPercentage,
			&i.Position,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentCode,
			&i.ChildCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenericChildren = `-- name: GetGenericChildren :many
SELECT id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
FROM item_structures
WHERE parent_item_id = $1
  AND parent_mask IS NULL
  AND is_active = TRUE
ORDER BY position, id
`

// Retorna apenas os filhos GENÉRICOS (sem máscara) de um pai.
func (q *Queries) GetGenericChildren(ctx context.Context, parentItemID int64) ([]ItemStructure, error) {
	rows, err := q.db.QueryContext(ctx, getGenericChildren, parentItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemStructure
	for rows.Next() {
		var i ItemStructure
		if err := rows.Scan(
			&i.ID,
			&i.ParentItemID,
			&i.ChildItemID,
			&i.ParentMask,
			&i.Quantity,
			&i.UnitOfMeasurement,
			&i.LossPercentage,
			&i.Position,
			&i.Notes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentCode,
			&i.ChildCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemCodeAndDescription = `-- name: GetItemCodeAndDescription :one
SELECT
    i.code::text AS code,
    COALESCE(
            p.pdm_description_technique,
            i.code::text
    ) AS description
FROM items i
         LEFT JOIN item_structures s
                   ON s.child_item_id = i.id
                       AND s.is_active = true
         LEFT JOIN items p
                   ON p.id = s.parent_item_id
WHERE i.id = $1
ORDER BY s.position ASC
    LIMIT 1
`

type GetItemCodeAndDescriptionRow struct {
	Code        string
	Description string
}

// Busca código e descrição técnica de um item pelo ID.
func (q *Queries) GetItemCodeAndDescription(ctx context.Context, id int64) (GetItemCodeAndDescriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getItemCodeAndDescription, id)
	var i GetItemCodeAndDescriptionRow
	err := row.Scan(&i.Code, &i.Description)
	return i, err
}

const getItemMaskAnswersByValue = `-- name: GetItemMaskAnswersByValue :many
SELECT
    ima.question_id,
    ima.position,
    ima.option_id
FROM item_masks im
JOIN item_mask_answers ima ON ima.mask_id = im.id
WHERE im.item_id    = $1   -- item pai
  AND im.mask = $2   -- ex: '100#100#50'
ORDER BY ima.position
`

type GetItemMaskAnswersByValueParams struct {
	ItemID int64
	Mask   string
}

type GetItemMaskAnswersByValueRow struct {
	QuestionID int64
	Position   int32
	OptionID   int64
}

// Retorna as respostas de uma máscara específica de um item,
// usado para propagar a máscara do pai para os filhos.
func (q *Queries) GetItemMaskAnswersByValue(ctx context.Context, arg GetItemMaskAnswersByValueParams) ([]GetItemMaskAnswersByValueRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemMaskAnswersByValue, arg.ItemID, arg.Mask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemMaskAnswersByValueRow
	for rows.Next() {
		var i GetItemMaskAnswersByValueRow
		if err := rows.Scan(&i.QuestionID, &i.Position, &i.OptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemQuestions = `-- name: GetItemQuestions :many
SELECT
    iq.question_id,
    iq.position
FROM item_questions iq
WHERE iq.item_id = $1
ORDER BY iq.position
`

type GetItemQuestionsRow struct {
	QuestionID int64
	Position   int32
}

// Retorna as perguntas associadas a um item, ordenadas por posição.
// Usado para calcular a máscara do filho com base nas respostas do pai.
func (q *Queries) GetItemQuestions(ctx context.Context, itemID int64) ([]GetItemQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemQuestions, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemQuestionsRow
	for rows.Next() {
		var i GetItemQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStructureComponentByID = `-- name: GetStructureComponentByID :one
SELECT id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
FROM item_structures
WHERE id = $1
`

func (q *Queries) GetStructureComponentByID(ctx context.Context, id int64) (ItemStructure, error) {
	row := q.db.QueryRowContext(ctx, getStructureComponentByID, id)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentItemID,
		&i.ChildItemID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Position,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
	)
	return i, err
}

const hasCyclicReference = `-- name: HasCyclicReference :one
WITH RECURSIVE ancestors(ancestor_id) AS (
    SELECT s.parent_item_id
    FROM item_structures s
    WHERE s.child_item_id = $1::bigint
    AND s.is_active = TRUE

UNION ALL

SELECT s.parent_item_id
FROM item_structures s
         JOIN ancestors ON s.child_item_id = ancestors.ancestor_id
WHERE s.is_active = TRUE
    )
SELECT EXISTS (
    SELECT 1
    FROM ancestors
    WHERE ancestor_id = $2::bigint
) AS has_cycle
`

type HasCyclicReferenceParams struct {
	Column1 int64
	Column2 int64
}

// Verifica se adicionar child_item_id como filho de parent_item_id
// criaria uma referência circular na árvore BOM.
// Retorna TRUE se houver ciclo (operação deve ser BLOQUEADA).
func (q *Queries) HasCyclicReference(ctx context.Context, arg HasCyclicReferenceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasCyclicReference, arg.Column1, arg.Column2)
	var has_cycle bool
	err := row.Scan(&has_cycle)
	return has_cycle, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS (
    SELECT 1
    FROM items
    WHERE id = $1
) AS "exists"
`

func (q *Queries) ItemExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, itemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateStructureComponent = `-- name: UpdateStructureComponent :one
UPDATE item_structures
SET
    quantity            = $2,
    unit_of_measurement = $3,
    loss_percentage     = $4,
    position            = $5,
    notes               = $6,
    updated_at          = NOW()
WHERE id = $1
  AND is_active = TRUE
RETURNING id, parent_item_id, child_item_id, parent_mask, quantity, unit_of_measurement, loss_percentage, position, notes, is_active, created_by, created_at, updated_at, parent_code, child_code
`

type UpdateStructureComponentParams struct {
	ID                int64
	Quantity          float64
	UnitOfMeasurement string
	LossPercentage    float64
	Position          int32
	Notes             sql.NullString
}

func (q *Queries) UpdateStructureComponent(ctx context.Context, arg UpdateStructureComponentParams) (ItemStructure, error) {
	row := q.db.QueryRowContext(ctx, updateStructureComponent,
		arg.ID,
		arg.Quantity,
		arg.UnitOfMeasurement,
		arg.LossPercentage,
		arg.Position,
		arg.Notes,
	)
	var i ItemStructure
	err := row.Scan(
		&i.ID,
		&i.ParentItemID,
		&i.ChildItemID,
		&i.ParentMask,
		&i.Quantity,
		&i.UnitOfMeasurement,
		&i.LossPercentage,
		&i.Position,
		&i.Notes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.ChildCode,
	)
	return i, err
}
