// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: structure_query.sql

package sqlc

import (
	"context"
)

const getMaskAnswersByItemAndValue = `-- name: GetMaskAnswersByItemAndValue :many
SELECT
    ima.question_id,
    ima.option_id,
    ima.position,
    qo.value AS option_value
FROM item_masks im
         JOIN item_mask_answers ima ON ima.mask_id = im.id
         JOIN question_options   qo ON qo.id      = ima.option_id
WHERE im.item_code = $1
  AND im.mask      = $2
ORDER BY ima.position
`

type GetMaskAnswersByItemAndValueParams struct {
	ItemCode int64
	Mask     string
}

type GetMaskAnswersByItemAndValueRow struct {
	QuestionID  int64
	OptionID    int64
	Position    int32
	OptionValue string
}

// JOIN obrigatório: sem option_value a propagação gera "3#7" ao invés de "1.94M#1.94M".
// Nome diferente de GetItemMaskAnswersByValue (sem option_value) em structure.sql.
func (q *Queries) GetMaskAnswersByItemAndValue(ctx context.Context, arg GetMaskAnswersByItemAndValueParams) ([]GetMaskAnswersByItemAndValueRow, error) {
	rows, err := q.db.Query(ctx, getMaskAnswersByItemAndValue, arg.ItemCode, arg.Mask)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaskAnswersByItemAndValueRow
	for rows.Next() {
		var i GetMaskAnswersByItemAndValueRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.OptionID,
			&i.Position,
			&i.OptionValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
