// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package sqlc

import (
	"context"
)

const createTest = `-- name: CreateTest :one
INSERT INTO tests DEFAULT VALUES
RETURNING id, created_at
`

func (q *Queries) CreateTest(ctx context.Context) (Test, error) {
	row := q.db.QueryRowContext(ctx, createTest)
	var i Test
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getTestByID = `-- name: GetTestByID :one
SELECT id, created_at
FROM tests
WHERE id = $1
`

func (q *Queries) GetTestByID(ctx context.Context, id int64) (Test, error) {
	row := q.db.QueryRowContext(ctx, getTestByID, id)
	var i Test
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listTests = `-- name: ListTests :many
SELECT id, created_at
FROM tests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTests(ctx context.Context, arg ListTestsParams) ([]Test, error) {
	rows, err := q.db.QueryContext(ctx, listTests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Test
	for rows.Next() {
		var i Test
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
