// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouse.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouse (
    name,
    description,
    code,
    types,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, code, name, active, created_at, created_by, description, types
`

type CreateWarehouseParams struct {
	Name        string
	Description string
	Code        string
	Types       string
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, createWarehouse,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.Types,
		arg.CreatedBy,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Description,
		&i.Types,
	)
	return i, err
}

const existsWarehouseByName = `-- name: ExistsWarehouseByName :one
SELECT id, name, createdby, complement_a_id, complement_b_id, created_at
FROM questions
WHERE name = $1
`

func (q *Queries) ExistsWarehouseByName(ctx context.Context, name string) (Question, error) {
	row := q.db.QueryRowContext(ctx, existsWarehouseByName, name)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Createdby,
		&i.ComplementAID,
		&i.ComplementBID,
		&i.CreatedAt,
	)
	return i, err
}
