// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouse.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouse (
    code,
    description,
    location,
    type,
    disposition,
    reservation_allowed,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, code, active, created_at, created_by, description, types, location, type, disposition, reservation_allowed
`

type CreateWarehouseParams struct {
	Code               string
	Description        string
	Location           WarehouseLocation
	Type               WarehouseType
	Disposition        bool
	ReservationAllowed bool
	CreatedBy          uuid.UUID
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, createWarehouse,
		arg.Code,
		arg.Description,
		arg.Location,
		arg.Type,
		arg.Disposition,
		arg.ReservationAllowed,
		arg.CreatedBy,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Description,
		&i.Types,
		&i.Location,
		&i.Type,
		&i.Disposition,
		&i.ReservationAllowed,
	)
	return i, err
}

const existsWarehouseByCode = `-- name: ExistsWarehouseByCode :one
SELECT EXISTS (
    SELECT 1
    FROM warehouse
    WHERE code = $1
)
`

func (q *Queries) ExistsWarehouseByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsWarehouseByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
